language: haskell

ghc:
  - "8.6.5"

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

install:
  - cabal install hakyll

script:
  - cabal build
  - cabal run site build
